### ISSUE TITLE
"TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by oti5** [JonPizza/trade-ogre-trader#2]
```[ 202437 14:54 ] [!] Order cancelled for all
Traceback (most recent call last):
  File "/home/farcry/trade-ogre-trader/trader.py", line 177, in <module>
    algo_one()
  File "/home/farcry/trade-ogre-trader/trader.py", line 164, in algo_one
    buy_low(c)
  File "/home/farcry/trade-ogre-trader/trader.py", line 151, in buy_low
    price = get_day_low(coin) + 0.00000001
  File "/home/farcry/trade-ogre-trader/trader.py", line 138, in get_day_low
    binance_day_low = float(binance.get_market_info(coin)['lowPrice'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by oti5** [comment]
```
[ 202437 14:54 ] [!] Order cancelled for all
```
